version: '3.7'

services:
   balancer_api:
    image: "registry.gitlab.com/stacrypt/redemption/balancer/stage:latest"
    container_name:  balancer_api
    depends_on:
      balancer_db:
        condition: service_healthy
    networks:
      stacloud_net:
        ipv4_address: 192.168.18.162
    healthcheck:
      test: curl --silent --fail http://localhost/health || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    env_file:
      - .env     
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__PostgreSQL
    restart: always
    mem_limit: 2g
    
   balancer_db:
    image: postgres
    container_name: balancer_db
    restart: always
    command: postgres -c 'max_connections=2500'
    environment:
      POSTGRES_DB: Balancer
      POSTGRES_USER: balancer
      POSTGRES_PASSWORD: P@SSW0rd
      PGDATA: /data/postgres
    volumes:
      - ./data/db:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      stacloud_net:
        ipv4_address: 192.168.18.163
networks:
 stacloud_net:
  name: stacloud_net
  external: true
  driver: bridge
  ipam:
    driver: default
    config:
      - subnet: 192.168.18.0/24